-- I N S E R C C I O N  D E  D A T O S

INSERT INTO ama_clientes 
VALUES(1,'Manuel','Fernandez','n','1990-01-10',345346456,'manuel.fernandez@gmail.com','Garcia'),
(2,'Nicolas','Setien','e','1985-07-22',987654321,'nicolas.setien@hotmail.com','Sandoval'),
(3,'Andrea','Rodriguez','n','1992-03-15',456789012,'andrea.fernandez@outlook.com','Fernandez'),
(4,'Paul','Ramirez','n','1988-11-05',321098765,'paul.ramirez@gmail.com','Santos'),
(5,'Carlos','Gonzalez','e','1996-09-18',210987654,'carlos.gonzalez@apple.com','Perez'),
(6,'Gabriela','Ortiz','n','1989-04-03',876543210,'gabriela.ortiz@hotmail.com','Gomez'),
(7,'Ricardo','Morales','n','1997-12-16',234567890,'ricardo.morales@outlook.com','Hernandez'),
(8,'Luis','Mendez','e','1993-08-07',543210987,'luis.mendez@apple.com','Reyes'),
(9,'Alejandro','Vargas','n','1991-02-28',789012345,'alejandro.vargas@gmail.com','Mendoza'),
(10,'Manuel','Flores','e','1998-12-10',890123456,'manuel.flores@apple.com','Lopez'),
(11,'Carolina','Ramos','n','1996-07-29',456289012,'carolina.ramos@outlook.com','Morales');

INSERT INTO ama_lugares_evento 
VALUES(1,'Baile Magico','Avenida Atlântica 1702, Hotel Copacabana Palace'),
(2,'Desfile de las escuelas de Samba grupo Especial','Sambódromo Profesor Darcy Ribeiro'),
(3,'Baile Gay del Scala','Scala nigth Club. Avenida Treze de Maio 23, Centro'),
(4,'The City Ball','Rua 13 de Maio, 23, Centro de Río de Janeiro.'),
(5,'Bola Preta Ball','Scala nigth Club. Avenida Treze de Maio 23, Centro'),
(6,'Desfile de las Escuelas de Samba Grupo de Acceso','Sambódromo Profesor Darcy Ribeiro'),
(7,'Beer Ball','Scala Rio Nightclub: Avenida Treze de Maio 23, Centro'),
(8,'Desfile del Bloque Noivas Do Parú','Praia de Itaguaçu'),
(9,'Desfile de los Campeones','Sambódromo Profesor Darcy Ribeiro'),
(10,'Ceremonia de Apertura','Sambódromo Profesor Darcy Ribeiro'),
(11,'Desfile de las Escuelas de Samba Infantiles','Sambódromo Profesor Darcy Ribeiro'),
(12,'Desfile de las Escuelas de Samba Grupo B','Sambódromo Profesor Darcy Ribeiro');

INSERT INTO ama_regiones_rio 
VALUES(1,'Region metropolitana','Abarca 20 municipios.'),
(2,'Zona Norte','Ubicada en el Norte del Macizo de Tijuca, al sur de la Baxiada Fluminende y al oeste de la Bahia de Guanabara'),
(3,'Zona Oeste','Cubre 12 barrios'),
(4,'Region Sudeste','es la segunda region mas pequeña del pais'),
(5,'Zona Central','Esta dividido por la Avenida Presidente Vargas, la principal avenida de la Region Central'),
(6,'Zona Sur','Cubre 12 barrios, tiene 639.522 poblacion'),
(7,'Region Noredeste','Contiene 9 estados');

INSERT INTO ama_empresas 
VALUES(1,'Bookers International','info@bookersinternational.com'),
(2,'Rio Maximo','info@riomaximo.com'),
(3,'Rio ticket','Info@rio-Tickets.com'),
(4,'Carnavales Brasil','info@carnavales-brasil.com'),
(5,'Rio Carnaval Tickets','riocarnavaltickets@gmail.com'),
(6,'Trip advisor','northamericapr@tripadvisor.com'),
(7,'Ticket Rio','atendimento@ticketrio.com.br'),
(8,'Rio','info@riocarnaval.com'),
(9,'Viator','viatortravel');

INSERT INTO ama_autorizaciones 
VALUES(1,5000),
(2,2500),
(3,2000),
(4,3000),
(5,5000),
(6,1000),
(7,1500),
(8,2000),
(9,5000);

INSERT INTO ama_tipos_entradas 
VALUES(1,1,'SL',2,1,'e','A'),
(2,2,'SL',2,1,'c','A'),
(3,3,'SL',2,2,'e','B'),
(4,4,'SL',2,2,'c','B'),
(5,5,'SL',2,3,'e','C'),
(6,6,'SL',2,3,'c','C'),
(7,7,'GP',3,4,'a','A/B'),
(8,8,'GP',3,5,'e','C/D'),
(9,9,'GP',3,4,'c','A/B'),
(10,1,'GP',3,5,'a','C/D'),
(11,2,'GP',3,4,'e','A/B'),
(12,3,'GP',3,5,'c','C/D'),
(13,4,'GP',4,4,'a','A/B'),
(14,5,'GP',4,5,'e','C/D'),
(15,6,'GP',4,4,'c','A/B'),
(16,7,'GP',4,5,'a','C/D'),
(17,8,'GP',4,4,'e','A/B'),
(18,9,'GP',4,5,'c','C/D'),
(19,1,'GP',5,4,'a','A/B'),
(20,2,'GP',5,5,'e','C/D'),
(21,3,'GP',5,4,'c','A/B'),
(22,4,'GP',5,5,'a','C/D'),
(23,5,'GP',5,4,'e','A/B'),
(24,6,'GP',5,5,'c','C/D'),
(25,7,'GP',7,4,'a','A/B'),
(26,8,'GP',7,5,'e','C/D'),
(27,9,'GP',7,4,'c','A/B'),
(28,1,'GP',7,5,'a','C/D'),
(29,2,'GP',7,4,'e','A/B'),
(30,3,'GP',7,5,'c','C/D'),
(31,4,'GP',9,4,'a','A/B'),
(32,5,'GP',9,5,'e','C/D'),
(33,6,'GP',9,4,'c','A/B'),
(34,7,'GP',9,5,'a','C/D'),
(35,8,'GP',9,4,'e','A/B'),
(36,9,'GP',9,5,'c','C/D'),
(37,1,'GP',11,4,'a','A/B'),
(38,2,'GP',11,5,'e','C/D'),
(39,3,'GP',11,4,'c','A/B'),
(40,4,'GP',11,5,'a','C/D'),
(41,5,'GP',11,4,'e','A/B'),
(42,6,'GP',11,5,'c','C/D'),
(43,7,'AN',6,6,'a',NULL),
(44,8,'AN',6,6,'e',NULL),
(45,9,'AN',6,6,'c',NULL),
(46,1,'GF',3,7,'a',NULL),
(47,2,'GF',3,7,'e',NULL),
(48,3,'GF',3,7,'c',NULL),
(49,4,'GF',4,7,'a',NULL),
(50,5,'GF',4,7,'e',NULL),
(51,6,'GF',4,7,'c',NULL),
(52,7,'GF',5,7,'a',NULL),
(53,8,'GF',5,7,'e',NULL),
(54,9,'GF',5,7,'c',NULL),
(55,1,'GF',7,7,'a',NULL),
(56,2,'GF',7,7,'e',NULL),
(57,3,'GF',7,7,'c',NULL),
(58,4,'GF',9,8,'a',NULL),
(59,5,'GF',9,8,'e',NULL),
(60,6,'GF',9,8,'c',NULL),
(61,7,'GF',11,7,'a',NULL),
(62,8,'GF',11,7,'e',NULL),
(63,9,'GF',11,7,'c',NULL);

INSERT INTO ama_reservas 
VALUES(1,1,'2011-01-15',1000.25,'2011-02-05'),
(2,2,'2012-06-30',2500.75,'2012-07-15'),
(3,3,'2013-04-12',1200.60,'2013-05-05'),
(4,4,'2012-09-02',800.35,'2012-09-20'),
(5,5,'2011-08-25',600.90,'2011-09-10'),
(6,6,'2012-11-09',1500.20,'2012-11-30'),
(7,7,'2013-07-17',300.75,'2013-08-05'),
(8,8,'2011-03-22',700.45,'2011-04-10'),
(9,9,'2013-10-14',1800.30,'2013-10-30');

INSERT INTO ama_escuelas_samba 
VALUES(1,'Beija-Flor','1948-12-25','Centro de Nilopolis','azul y blanco','es una escuela de samba brasileña del municipio deNilópolis, pero que lleva muchos años participando en el Carnaval de la ciudad de Río de Janeiro. Con catorce logros, la escuela asume la tercera mayor ganadora en el rol de los campeones del carnaval de Río de Janeiro, siendo la que más ganó en la "era sambódromo".',1),
(2,'Unidos da Tijuca','1931-12-31','Tijuca','amarillo y azul','es una escuela de samba en la ciudad de Río de Janeiro, Tiene 4 títulos de campeón del Grupo Especial del carnaval carioca',2),
(3,'Primera Estacion de Manguera','1928-04-28','Mangueira','verde y rosa','es una escuela de samba tradicional brasileña de la ciudad de Río de Janeiro, ocupa la posición de segundo mayor ganador en la lista de campeones del carnaval de Río de Janeiro',2),
(4,'Unidos de Vila Isabel','1946-04-04','Vila Isabel','banco y azul','es una de las escuelas de samba más tradicionales de la ciudad de Río de Janeiro, fue campeona del Grupo Especial Carnaval en 1988, 2006 y 2013.',2),
(5,'Academicos del Salgueiro','1953-03-05','Pandeiro','rojo y blanco','es una de las escuelas de samba más tradicionales de la ciudad de Río de Janeiro. Tiene nueve títulos de campeón del Grupo Especial del Carnaval de Río. la posición de cuarto mayor ganador en la lista de campeones del carnaval de Río de Janeiro.',2),
(6,'Emperatriz Leopoldinense','1959-03-06','Ramos','verde, blanco, dorado','es una escuela de samba de la ciudad de Rio de Janeiro, Imperatriz Leopoldinense es poseedora de nueve títulos de campeona del grupo principal del carnaval carioca, siendo que en 1980, 1989 y 2001 fue campeona obteniendo la máxima puntuación en todos los aspectos',2),
(7,'Juventud Independiente de Padre Miguel','1955-11-10','Padre Miguel','verde, blanco, amarillo','es una escuela de samba en la ciudad de Río de Janeiro. Dueña de seis logros (1979, 1985, 1990, 1991, 1996, 2017), la escuela se ubica como la séptima mayor ganadora del Carnaval de Campeones del Carnaval de Río de Janeiro.',3),
(8,'Unidos del Puerto de la Piedra','1978-03-08','Porto da Piedra','rojo, blanco','La asociación fue creada a partir de un equipo de fútbol. En Río, nunca ganó el título de campeona del grupo principal. Ya en São Gonçalo, fue campeona una vez, en el año 1982',4),
(9,'San Clemente','1961-01-25','Cidade Nova','negro, amarillo','es una escuela de samba brasileña de la ciudad de Río de Janeiro,u mejor colocación en el Grupo Especial del Carnaval fue el 6o lugar en 1990 con la trama "E o Samba Sambou" que criticaba la mercantilización del carnaval. En 2021, la escuela completa 23 participaciones entre las grandes escuelas del Grupo Especial, siendo que, por 11 veces consecutivas, entre 2011 y 2021.',5),
(10,'Academicos del Gran Rio','1988-09-22','Centro de Duqe de Caxias','verde, blanco, rojo','es una escuela de samba brasileña del municipio de Duque de Caxias, que desfila en el carnaval de la ciudad de Río de Janeiro, más precisamente en el Grupo Especial. Fue campeona del Grupo Especial del Carnaval por primera vez en la historia en 2022. También fue subcampeona en 2006, 2007, 2010 y 2020. La exaltación a la región amazónica ha sido recurrente en sus desfiles, inspirando las tramas de 1995, 1997, 2006 y 2008.',1),
(11,'Portela','1923-04-11','Madureira','azul, blanco','es una escuela de samba brasileña de la ciudad de Río de Janeiro. Portela es la mayor campeona del carnaval de Río de Janeiro, con 22 títulos',2),
(12,'Union de la Isla del Gobernador','1953-03-07','Cacuia','azul, blanco, rojo','es una escuela de samba de la ciudad de Río de Janeiro, campeona del grupo de acceso en dos ocasiones',2),
(13,'Renascer de Jacarepagua','1992-08-02','Tanque','rojo, blanco','es una escuela de samba en la ciudad de Río de Janeiro. campeón del grupo de acceso en el 2011',3),
(14,'Unidos de Viradouro','1946-06-24','Barreto','rojo, blanco','es una escuela de samba brasileña, fue dos veces campeona del Grupo Especial',1),
(15,'Estacio de Sa','1955-02-27','Estacio','rojo, blanco','es una escuela de samba brasileña de la ciudad de Río de Janeiro. Tiene el título de campeón del Grupo Especial de Río de Janeiro, conquistado en 1992, con el argumento "Paulicéia Desvairada - 70 años de Modernismo". También ganó siete veces la segunda división del carnaval carioca y dos veces la tercera división.',5),
(16,'Academicos de Cubango','1959-12-17','Cubango','verde, blanco','es una escuela de samba brasileña de la ciudad de Niterói, que desde los años ochenta participa del carnaval de Río,',1),
(17,'Academicos de Santa Cruz','1959-02-18','Santa Cruz','verde, blanco','es una escuela de samba brasileña de la ciudad de Río de Janeiro. Poseen 5 Títulos de Segunda División',3),
(18,'Imperio Serrano','1947-03-23','Madureira','verde, blanco','es una escuela de samba brasileña de la Zona Norte, Império Serrano es el cuarto mayor ganador de la juerga carioca, con nueve títulos de campeonato, También tiene cinco títulos de segunda división, Desfile por primera vez en 1948, siendo cuatro veces campeón en la primera cuatro desfiles que participaron',2),
(19,'Imperio de Tijuca','1940-12-08','Tijuca','verde, blanco','es una escuela de samba brasileña de la ciudad de Río de Janeiro. Su mejor colocación fue un cuarto lugar, logrado en su desfile debut, en 1946.',2),
(20,'Inocentes de Belford Roxo','1993-07-11','Parque Sao Vicente','azul, blanco, rojo','es una escuela de samba brasileña de la ciudad de Belford Roxo, que participa en el Carnaval de Río de Janeiro. un campeonato en segunda, tercera y cuarta división',1),
(21,'Academicos de Rocinha','1988-03-30','Sao Conrado','blanco, azul, verde','es una escuela de samba brasileña de la ciudad de Río de Janeiro. Un campeonato de segunda división, 4 campeonatos de tercera división, un campeonato de cuarta división y un',6),
(22,'Caprichosos de Pilares','1949-02-19','Pilares','azul royale, azul turquesa, Blanco','es una escuela de samba brasileña de la ciudad de Río de Janeiro. Su mejor ubicación en el Grupo Especial de Carnaval fue el 3er lugar en el Desfile Dominical en 1984.',2),
(23,'Alegria de la Zona Sur','1992-06-28','Copacabana','rojo, blanco, dorado','es una escuela de samba en la ciudad de Río de Janeiro. su característica más fuerte en sus tramas es el uso de temas que tratan el tema de la negrura, un campeonato en tercera, cuarta, quinta y dos en sexta división',6),
(24,'Paraiso de Tuiuti','1952-04-05','Sao Cristovao','azul, amarillo','Es una escuela de samba con sede en la ciudad de Río de Janeiro, Campeonato En Segunda División, Tres En Tercera División, Dos En Cuarta División',5),
(25,'Union del Parque Curicica','1993-03-01','Curicica','azul, rojo, blanco','es una escuela de samba de la ciudad de Río de Janeiro, campeonato de cuarta división',3),
(26,'Unidos de Padre Miguel','1957-11-12','Padre Miguel','rojo, blanco','es una escuela de samba en la ciudad de Río de Janeiro. Tiene seis campeonatos ganados en grupos de acceso.',3),
(27,'Arranco','1973-03-21','Engenho de Dentro','azul, blanco','es una escuela de samba de la ciudad de Río de Janeiro, una vez campeona del grupo B',2),
(28,'Sereno de Campo Grande','1996-02-12','Campo Grande','azul, blanco','es una escuela de samba de la ciudad de Río de Janeiro, campeona del grupo E en una ocasión',3),
(29,'Union de Jacarepagua','1956-11-15','Aperto de mao','verde, blanco','es una escuela de samba de la ciudad de Rio de Janeiro, Campeon de la serie D en dos ocasiones',2),
(30,'Tradicion','1984-10-01','Campinho','azul royal, azul turquesa, blanco, dorado, gris','es una escuela de samba de la ciudad de Río de Janeiro, fue campeona de segunda división en tres ocasiones. Su mejor ubicación en el grupo especial fue el sexto lugar en 1994.',2),
(31,'Dificil es el nombre','1973-10-31','Pilares','rojo, blanco','es una escuela de samba de la ciudad de Río de Janeiro, campeona del grupo B en una ocasión',3),
(32,'Juventud de Vicente Carvalho','1988-02-07','Aguia','verde, blanco','es una escuela de samba en la ciudad de Río de Janeiro. Cuenta con dos títulos de campeonato y tres subcampeonatos conseguidos en grupos de acceso. En 2002 ganó el Grupo D; y en 2007 Grupo C. Desfiló varias veces en Grupo B, nunca habiendo llegado a Serie A y Grupo Especial.',2),
(33,'Academicos de la tranquilidad','1969-11-10','Largo da Batalha','azul, blanco','es una escuela de samba de la ciudad de Niterói, fue cuatro veces campeona del Grupo Especial del Carnaval de Niterói. También tuvo otros dos títulos en el Niteroi Access Group. En el carnaval de Río de Janeiro, ganó cuatro campeonatos en grupos de acceso.',1),
(34,'Independientes de San Juan de Meriti','1975-03-26','Praca da Bandeira','azul, verde, blanco','es una escuela de samba de São João de Meriti, Campeona del grupo C, D y E',1),
(35,'Lins Imperial','1963-03-07','Aguia','verde, rosa','es una escuela de samba brasileña de la ciudad de Río de Janeiro, un campeonato en segunda división y 4 campeonatos en tercera división',2),
(36,'Infantes de Lins','1991-05-01','Lins de Vasconcelos','verde, rosa','es una escuela de samba infantil de la ciudad de Río de Janeiro. Campeon en el carnaval 2011 de la seccion infantil en la reedicion de la trama de samba Lins Imperial de 1991.',2),
(37,'Nueva Generacion del Estacio de Sa','1992-10-12','Estacio','rojo, blanco','es una escuela de samba para niños de la ciudad de Río de Janeiro. Subampeon en el carnaval 2011 de la seccion infantil en la reedicion de la trama de 1992 de Estácio de Sá.',2),
(38,'Inocentes de Caprichosos','1991-04-04','Pilares','azul royal, azul turquesa, blanco','es una escuela de samba para niños de la ciudad de Río de Janeiro. 3er lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 2004 de Caprichosos de Pilares.',2),
(39,'Pimpolhos de la Gran Rio','2002-08-10','Centro','verde, blanco, rojo','es una escuela de samba infantil y una organización no gubernamental, ubicada en la Rua Conde de Porto Alegre, en el centro de Caxias. 4to lugar en el carnaval del 2011 de la seccion infantil en la trama de "...nuestros cuentos...".',1),
(40,'Corazones Unidos del Ciep','1985-08-15','Mangueira','naranja, blanco, amarillo','es una escuela de samba para niños de la ciudad de Río de Janeiro.  5to lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 1997 de Uniao da Ilha do Governador.',2),
(41,'Desfiles de Guanabara','1996-06-06','Copacabana','azul, amarillo','es una escuela de samba para niños de la ciudad de Río de Janeiro. 6to lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 1998 de Académicos de Santa Cruz.',6),
(42,'Herederos de la Villa','1988-06-23','Coroa','azul claro, blanco','es una escuela de samba junior de la ciudad de Río de Janeiro. 7mo lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 1994 de Unidos de Vila Isabel.',2),
(43,'Aprendices del Sauce','1989-10-03','Andarai','blanco, rojo','es la escuela de samba junior de Academicos do Salgueiro. ubicada en la misma dirección del bloque Salgueiro, en la Zona Norte de la ciudad de Río de Janeiro. 8vo lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 1969 de Academicos do Salgueiro.',7),
(44,'Estrellita de la Juventud','1992-06-02','Padre Miguel','verde, blanco','es una escuela de samba para niños de la ciudad de Río de Janeiro. 9no lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 2002 de Mocidade.',3),
(45,'Petizes da Penha','2002-06-26','Penha','verde, blanco','es una escuela de samba junior de la ciudad de Río de Janeiro. 10mo lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 2006 de Flor da Mina do Andaraí.',2),
(46,'La niña de Cabucu','1991-07-14','Lins de Vasconcelos','azul, blanco','es la escuela de samba juvenil de Unidos do Cabucu, ubicada en la Zona Norte de la ciudad de Río de Janeiro. 11vo lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 1988 de Unidos do Cabucu.',2),
(47,'Hijos del Aguila','2001-07-31','Madureira','azul, blanco','es una escuela de samba para niños de la ciudad de Río de Janeiro. 12vo lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 1984 de Portela.',2),
(48,'Imperio del Futuro','1983-08-05','Madureira','verde, blanco','es una escuela de samba junior de la ciudad de Río de Janeiro. 13vo lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 1972 de Império Serrano.',2),
(49,'Manguera del mañana','1987-08-12','Mangueria','verde, rosa','es una escuela de samba junior de la ciudad de Río de Janeiro. 14vo lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 1994 de Mangueira.',2),
(50,'Tijuquinha do Borel','2002-06-19','Tijuca','Amarillo, azul','es una escuela de samba junior de la ciudad de Río de Janeiro. 15vo lugar en el carnaval del 2011 de la seccion infantil en la reedicion de la trama de 2005 de Unidos da Tijuca.',2),
(51,'Todavia hay niños en Vila Kennedy','1991-04-21','Vila Kennedy','rojo, blanco','es una escuela de samba para niños en la ciudad de Río de Janeiro. reeditó varias tramas de Portela en diferentes años de los carnavales. En 2015 realizó un desfile sobre el carnaval Juegos Olímpicos',3),
(52,'Unidos de Vila Santa Tereza','1956-12-20','Rocha Miranda','azul, blanco, amarillo','es una destacada escuela de samba de Río de Janeiro, Brasil, fundada en 1960. Representa y celebra la cultura y tradiciones del barrio de Santa Tereza. Conocida por su pasión y energía, ha ganado reconocimiento en el carnaval carioca. Su batería y samba-enredo son emblemáticos. Realizan desfiles coloridos y coreografías elaboradas. Además del carnaval, se involucran en actividades comunitarias y promueven la inclusión social. Unidos de Vila Santa Tereza es un símbolo de identidad y una fuente de inspiración para su comunidad.',2),
(53,'Miel del futuro','2003-11-06','Maria de Gracia','negro, amarillo','es una escuela de samba para niños de la ciudad de Río de Janeiro. Fue la tercera escuela en desfilar en 2012 con una reedición de Imperatriz, la samba de 1999.',2);

INSERT INTO ama_hist_grupos 
VALUES(9,'2011-03-06','e',NULL),
(6,'2011-03-06','e',NULL),
(11,'2011-03-06','e',NULL),
(2,'2011-03-06','e',NULL),
(4,'2011-03-06','e',NULL),
(3,'2011-03-06','e',NULL),
(12,'2011-03-07','e',NULL),
(5,'2011-03-07','e',NULL),
(7,'2011-03-07','e',NULL),
(10,'2011-03-07','e',NULL),
(8,'2011-03-07','e',NULL),
(1,'2011-03-07','e',NULL),
(23,'2011-03-05','a',NULL),
(13,'2011-03-05','a',NULL),
(14,'2011-03-05','a',NULL),
(17,'2011-03-05','a',NULL),
(19,'2011-03-05','a',NULL),
(20,'2011-03-05','a',NULL),
(16,'2011-03-05','a',NULL),
(15,'2011-03-05','a',NULL),
(18,'2011-03-05','a',NULL),
(21,'2011-03-05','a',NULL),
(22,'2011-03-05','a',NULL);

INSERT INTO ama_protagonistas 
VALUES(1,'Milton','Rodrigues','m','1980-04-19',82746351,'Da Silva',1),
(2,'Viviane','Araujo','f','1975-03-25',93685724,NULL,5),
(3,'Bruno','Bruna','f','1980-07-23',54218936,NULL,9),
(4,'Sabrina','Sato','f','1981-02-04',73824695,NULL,4),
(5,'Alexandre','Louzada','m','1957-12-15',61938475,'Oliveira',1),
(6,'Paulo','Barros','m','1962-05-14',42791583,NULL,2),
(7,'Mauro','Quintaes','m','1958-08-12',98537162,NULL,3),
(8,'Rosa','Magalhaes','f','1947-01-08',61354987,NULL,4),
(9,'Renato','Lage','m','1949-05-21',75931648,'Souza',5),
(10,'Max ','Lopes','m','1949-05-15',28419673,NULL,6),
(11,'Cid','Carvalho','m','1967-03-19',94673128,NULL,7),
(12,'Paulo','Menezes','m','1971-09-19',58346729,NULL,8),
(13,'Fabio ','Ricardo','m','1975-09-01',72189436,NULL,9),
(14,'Cahe ','Rodrigues','m','1976-06-30',36549821,NULL,10),
(15,'Roberto','Szaniecki','m','1961-10-30',47891632,NULL,11),
(16,'Alex','De Souza','m','1965-09-30',63921857,'Rodriguez',12),
(17,'Jack ','Vasconcelos','m','1977-05-13',89214357,NULL,14),
(18,'Marcus','Ferreira','m','1984-07-28',51693872,NULL,15),
(19,'Jaime ','Cezario','m','1963-10-25',73682915,NULL,16),
(20,'Carlinhos ','Muvucs','m','1983-09-28',28496137,NULL,17),
(21,'Alexandre','Colla','m','1958-07-17',93742861,NULL,18),
(22,'Severo','Luzardo','m','1962-06-29',65831429,NULL,19),
(23,'Cristiano ','Bara','m','1973-02-11',49217658,'Costa',20),
(24,'Luiz','Bruno','m','1969-03-19',83724619,NULL,21),
(25,'Amauri','Santos','m','1951-05-15',56198437,NULL,22),
(26,'Lane','Santana','m','1974-11-15',29478631,NULL,23),
(27,'Eduardo','Goncalves','m','1969-01-22',87463592,NULL,24),
(28,'Fabio ','Santos','m','1982-04-19',51983764,NULL,25),
(29,'Morgana ','Bastos','m','1976-03-25',28795416,NULL,26),
(30,'Adilson','Pinto','m','1981-07-23',64821973,NULL,28),
(31,'Augusto ','de Oliveira','m','1982-02-04',92436857,NULL,30),
(32,'Luiz ','Cavalcante','m','1959-12-15',48531796,NULL,31),
(33,'Alexandre ','Rangel','m','1964-05-14',63987142,'Santos',32),
(34,'Fabianno','Santana','m','1959-08-12',29381467,NULL,33),
(35,'Robson','Goulart','m','1949-01-08',74832619,NULL,34),
(36,'Eduardo','Minucci','m','1951-05-21',51628473,NULL,35),
(37,'Claudinho','de Souza','m','1972-05-04',82735914,NULL,1),
(38,'Selminha','Sorriso','f','1971-05-30',36479125,NULL,1),
(39,'Fabio ','Junior','f','1973-09-19',54891673,NULL,13),
(40,'Jessica','Ferreira','m','1961-12-03',81475329,NULL,13),
(41,'Ze','Roberto','f','1970-04-26',71549283,NULL,24),
(42,'Livia','Ferreira','m','1985-08-07',36825794,NULL,24);

INSERT INTO ama_carnavales_anuales
VALUES(2011,'2011-03-04','2011-03-12',1,2),
(2012,'2012-02-17','2012-02-25',1,3),
(2013,'2013-02-08','2013-02-16',1,4);

INSERT INTO ama_eventos 
VALUES(2011,1,1,'g','2011-03-05','22:00',18,'s','Se caracteriza por su energía, ritmo y espiritualidad. Los bailarines utilizan movimientos fluidos y expresivos que reflejan una conexión profunda con la música y los ritmos africanos, como la samba, el candomblé y la capoeira. A través de la danza, se busca establecer una comunicación con lo divino y los espíritus, canalizando su poder y energía para el beneficio personal y colectivo.',2410.82),
(2011,2,2,'d','2011-03-05','21:00',10,'s','Los coreógrafos y diseñadores de cada una de las 12 escuelas preparan la escena del espectáculo en busca del codiciado título de campeones, que tanta fama y fortuna aporta a la escuela campeona.',630.59),
(2011,11,6,'d','2011-03-05','21:00',10,'s','lleva a cabo algunas de las actuaciones más fascinantes del Desfile de Samba si bien a la sombra de las escuelas del Grupo Especial. la mejor escuela formará parte del Grupo Especial el año siguiente.',345.69),
(2012,3,3,'g','2012-02-21','23:00',18,'s','En la noche del Gay Ball, la alfombra roja fuera del Scala Nightclub se reemplaza por una rosa, ya que este evento notoriamente fabuloso atrae a grandes multitudes de drag queens y sus admiradores. Los escandalosos atuendos de la notoria “alfombra rosa” del Gay Scala Ball atraen a los medios ya las celebridades. Drag kings y queens compiten por la atención mientras hacen sus grandes entradas en el Scala Nightclub.',1000),
(2012,4,4,'g','2012-02-18','09:00',10,'s','El baile contará con distinguidos sambistas del famoso bloco Bola Preta tocando las canciones bohemias que los convierten en algunos de los artistas más reconocidos de Brasil. Se espera que grandes nombres como João Roberto Kelly, Luiz Camillo y Dominguinhos se presenten en el inolvidable Cordão do Bola Preta Ball.',1200),
(2012,7,7,'g','2012-02-20','10:30',18,'s','Es una noche dedicada a una de las bebidas favoritas de los cariocas: la Cerveja (cerveza). En este el ¡Viva la Cerveza! Ball disfrutarás de un suministro ilimitado de cerveza gratis y de fondo escucharás el ritmo palpitante de la mejor música del Carnaval de Río.',500),
(2012,8,8,'d','2012-02-19','22:00',10,'s','Es una mezcla única de arte, cultura, música y celebración.',160),
(2012,10,2,'d','2012-02-20','21:00',10,'s','Los coreógrafos y diseñadores de cada una de las 12 escuelas preparan la escena del espectáculo en busca del codiciado título de campeones, que tanta fama y fortuna aporta a la escuela campeona.',325.65),
(2013,5,5,'g','2013-02-17','23:00',18,'s','Una fiesta dedicada a la banda callejera más grande y popular de Rio Canrnival. Teniendo lugar la noche anterior al desfile de la calle Cordão do Bola Preta, el baile contará con distinguidos sambistas del famoso bloco Bola Preta tocando las canciones bohemias que los convierten en algunos de los artistas más reconocidos de Brasil.',400),
(2013,6,6,'d','2013-02-09','21:00',10,'s','lleva a cabo algunas de las actuaciones más fascinantes del Desfile de Samba si bien a la sombra de las escuelas del Grupo Especial. la mejor escuela formará parte del Grupo Especial el año siguiente.',630.59),
(2013,9,9,'d','2013-02-09','21:00',10,'s','En este desfile, las escuelas de samba campeonas de cada ciudad tienen la oportunidad de mostrar nuevamente sus elaboradas y espectaculares presentaciones. Cada escuela de samba presenta su tema central a través de carrozas, trajes elaborados, música y danzas.',385.73),
(2013,12,9,'d','2013-02-09','21:00',10,'s','las seis escuelas principales regresan para la contienda final en el Desfile de Campeones el sábado posterior.',206.4);

INSERT INTO ama_participaciones 
VALUES(2,2011,1,'2:50:00',12,1,'La Simplicidad de Un Rey,  El desfile de 2011 homenajeó al cantante y compositor Roberto Carlos, retratando la vida y la obra del artista.','A Simplicidade de Um ReiTínhamos na final dois sambas que dividiram a preferência dos segmentos. Como sempre, toda a comunidade foi ouvida. A decisão foi por critérios técnicos e estou confiante que a Beija-Flor continuará recebendo notas máximas dos julgadores de samba-enredo, como vem acontecendo nos últimos quinze anos. Espero que o Roberto (Carlos) goste do samba e de tudo o que está sendo feito para ele.'),
      (2,2011,2,'0:30:00',4,2,'Unidos Da tijuca, actual campeona del grupo especial del carnaval de Río de Janeiro, homenajeará en la edición 2011 del carnaval más importante del mundo al cineasta y actor de cine de terror conocido como Zé do Caixão. Los desfiles y las alegorías del desfile 2011 de Unidos da Tijuca estarán inspiradas en las películas y en el particular mundo de este ícono del terror brasileño.','Esta Noite Levarei Sua AlmaTá com medo de quê?O filme já vai começarVocê foi convidadoCaronte no barco não pode esperarApague a luz, a guerra começouSob o capuz, delira o diretorNo filme que passa piada em cartazPavor me abraça, isso não se fazNo espaço se vai, é a força que vemMeu medo não teme ninguémÉ o boom! Quem não viu? A casa caiuCom a bomba na mão o vilão explodiuO plano de fuga é jogo de cenaUm Deus nos acuda... Agita o cinemaEle volta revolta, mistério no arDos milharais uma estranha visãoMais uma vez olha a encenaçãoMorrer de amar faz o povo gargalharPare! Eu pego vocês, grita o mal condutorMas deu tudo errado, não há outro lado Esse povo me enganouEu sou brasileiro, amor tijucanoRoteiro sem ponto final Coitado o barqueiro entrou pelo cano E brinca no meu carnaval Eu sou Tijuca, estou em cartaz Sucesso na tela meu povo é quem fazSou do Borel da gente guerreira A pura cadência levanta poeira'),
      (2,2011,3,'2:50:00',6,3,'""El hijo fiel, siempre Mangueira"", dedicado a Nelson Cavaquinho, uno de los insignes compositores de esa popular escuela.','O Filho Fiel, Sempre Mangueira Mangueira é nação, é comunidade! Minha festa, teu samba, ninguém vai calar! Sou teu filho fiel, Estação Primeira Por tua bandeira, vou sempre lutar! Quis o Criador me abençoar Fazer de mim um menestrel Traço o meu passo no compasso Do surdo de primeira Sou Mangueira! Trilhei ruas e vielas Morro de alegria, de emoção! Procurando harmonia, encontrei a poesia E me entreguei à boemia No Buraco Quente, Olaria e Chalé Com meus parceiros de fé Trago violão No Zicartola, opinião! Se te encantei com meu talento Acabo te vendendo uma canção Passei aquela dor venceu espinhos Amor perfeito em nosso ninho Que foi desfeito ao luar! Prazer, me chamam Nelson Cavaquinho Tatuei em meu caminho Seletas obras musicais! Sonhei, que Folhas Secas cobriam meu chão Pra delírio dessa multidão Impossível não emocionar! Chorei, ao voltar para minha raiz Ao teu lado eu sou mais feliz Pra sempre vou te amar!'),
      (2,2011,4,'1:40:00',5,4,'con ""Mitos e historias entrelazadas por los cabellos"", sobre la importancia de las cabelleras en las distintas culturas y que cuenta con la participación de la modelo Gisele Bundchen.','Mitos e Histórias Entrelaçadas pelos Fios de Cabelo Respeite a coroa em meu pavilhão A desfilar na avenida Carrega os fios de Isabel, da liberdade É minha vida, é a Vila! O brilho, a raiz, a sedução O universo em sua formação Nas longas madeixas de Shiva Dos ritos aos astros Os mitos que enlaçam Antigas tradições Festejando novas gerações Sansão, forte, se apaixonou O corte enfim revelou Dalila Trança a paixão, o nobre fiel Às lágrimas viu Rapunzel mais linda A força e o amor cobriram o corpo Vencendo as rédeas da exploração Perucas no Egito, poder divinal No luxo da França, adornam o Rei Sol Aqui, entrelaçado em ouro Vi florir a alforria, sonhos colorir Em tantas formas buscar perfeição Para os poetas a inspiração, afinal Charme e tom sensual Moldaram a beleza do meu carnaval Modéstia à parte, amigo, sou da Vila Quem é bamba nem sequer vacila Envolvido entre cabelos, me sinto arrepiar Feitiço refletindo no olhar'),
      (2,2011,5,'22:10:00',8,5,'Académicos de Salgueiro, con su desfile ""Río en el cine"", dedicó al filme de animación una carroza titulada ""Volando sobre Río"" en la que la enorme ave azul batía sus alas y observaba con su profunda mirada al público que presenciaba el espectáculo.','Salgueiro Apresenta: O Rio no Cinema Salgueiro Apresenta o Rio no Cinema Já não há mais lugar para nos ver na passarela Cada um é um astro que entra em cena No maior espetáculo da tela A Cinelândia reencontrar A luz de apaga acende a vida Projeta sonhos na Avenida A Terra em Transe mostrou visão singular E o tesouro de Atlândita Foi abraçado pelo mar Onde está? Diz aí Carlota Joaquinha veio descobrir Na busca o bonde da Lapa Madame Satã Pequena Notável requebra até de manhã Em um simples instante Orfeu vence as dores em som dissonante E as cordas do seu violão Silenciam para o amanhecer Brilha o sol de um dia de verão Salta aos olhos outra dimensão Revoada risco o céu e faz Amigos alados canto de paz Maneiro deu a louca em Copacabana Vi beijo do homem na Mulher Aranha E o King Kong no relógio da Central Meu Salgueiro, o Oscar sempre é da Academia Põe o Bip-Bop na Furiosa Bateria Aqui tudo acaba em carnaval O cenário é perfeito De braços abertos sobre a Guanabara O filme mostrou maravilhosa chanchada Sob a direção do Redentor'),
      (11,2011,6,'22:10:00',2,6,'una de las más prestigiosas, que apuesta por el tema ""Bailar samba hace bien a la salud"" y usa como hilo conductor la historia de la medicina desde la época del antiguo Egipto.','Imperatriz Adverte: Sambar Faz Bem à Saúde! Um ritual de magia Oh, Mãe África Do teu ventre nascia o poder de curar Despertam as antigas civilizações A cura pela fé nas orações Mistérios da vida, o homem a desvendar A mão da ciência ensina O mundo não pode parar Uma viagem no tempo a me levar O valor do pensamento a me guiar O toque do artista no Renascimento Surge um novo jeito de pensar! Luz, semeando a ciência A razão na essência, o dever de cuidar! Luz, a medida que avança Uma nova esperança que nos leva a sonhar! Segredo, a Chave da Vida Perfeição esculpida, iludindo o olhar Onde a medicina vai chegar? No Carnaval, uma injeção de alegria Dividida em doses de amor É a minha Escola a me chamar, doutor Posso ouvir o som da bateria O remédio pra curar a minha dor Eu quero é sambar A cura do corpo e da alma no samba está Sou Imperatriz, sou raiz e não posso negar Se alguém me decifrar É verde e branco meu DNA'),
      (11,2011,7,'23:20:00',9,7,'Parábola dos Divinos Semeadores Tá todo mundo aí? Levanta a mão Quem é filho desse chão Chegou a Mocidade fazendo a alegria do povo Meu coração vai disparar de novo Uma luz no céu brilhou, liberdade! Meu coração venceu o medo O que era gelo se tornou felicidade A esperança se espalhando pelo chão A natureza tem mistérios e magias Rituais, feitiçarias, deuses a me abençoar Levado pela luz da estrela guia Eu vou por onde a semente germinar O que eu plantei, o mundo colheu Um milagre aconteceu A vida celebrou um ideal E a fartura se transforma em festival O que eu plantei, o mundo colheu Um milagre aconteceu A vida celebrou um ideal E a fartura se transforma em festival Festa de Ísis, a farra do vinho Em Roma a semente foi brotar Mudaram meu papel, oh Padre Miguel! Hoje ninguém vai me censurar No baile da máscara negra Até a nobreza teve que engolir Meu Brasil, de norte a sul sou manifestação Aonde vou arrasto a multidão De cada cem só não vem um Vou voltar, um dia ao espaço sideral E reviver o meu ziriguidum, em alto astral','Parábola dos Divinos Semeadores Tá todo mundo aí? Levanta a mão Quem é filho desse chão Chegou a Mocidade fazendo a alegria do povo Meu coração vai disparar de novo Uma luz no céu brilhou, liberdade! Meu coração venceu o medo O que era gelo se tornou felicidade A esperança se espalhando pelo chão A natureza tem mistérios e magias Rituais, feitiçarias, deuses a me abençoar Levado pela luz da estrela guia Eu vou por onde a semente germinar O que eu plantei, o mundo colheu Um milagre aconteceu A vida celebrou um ideal E a fartura se transforma em festival O que eu plantei, o mundo colheu Um milagre aconteceu A vida celebrou um ideal E a fartura se transforma em festival Festa de Ísis, a farra do vinho Em Roma a semente foi brotar Mudaram meu papel, oh Padre Miguel! Hoje ninguém vai me censurar No baile da máscara negra Até a nobreza teve que engolir Meu Brasil, de norte a sul sou manifestação Aonde vou arrasto a multidão De cada cem só não vem um Vou voltar, um dia ao espaço sideral E reviver o meu ziriguidum, em alto astral'),
      (2,2011,8,'1:40:00',11,8,'presentó un homenaje a la actriz y directora brasileña Maria Clara Machado, con el tema ‘El sueño siempre viene para quien sueña‘, creado por el carnavalesco Paulo Menezes.','O Sonho Sempre Vem pra quem Sonhar... Tudo pode ser Se quiser será Sonhos sempre vêm Pra quem sonhar Tudo pode ser Só basta acreditar Tudo que tiver que ser, será Tudo que eu fizer Eu vou tentar melhor do que já fiz Esteja o meu destino onde estiver Eu vou buscar a sorte e ser feliz Tudo que eu quiser O cara lá de cima vai me dar Me dar toda coragem que puder Que não me falte forças pra lutar Vamos com você Nós somos invencíveis, pode crer Todos somos um E juntos não existe mal nenhum Vamos com você Nós somos invencíveis, pode crer O sonho está no ar O amor me faz cantar Lua de cristal Que me faz sonhar Faz de mim estrela Que eu já sei brilhar Lua de cristal Nova de paixão Faz a minha vida Cheia de emoção Lua de cristal Que me faz sonhar Faz de mim estrela Que eu já sei brilhar'),
      (2,2011,9,'21:00:00',1,9,'Sao Clemente que para este año escogió una temática con la que pretende rendir homenaje a la ciudad bajo el eslogan ""Río, bendecido por Dios y bonito por naturaleza"".','O Seu, o Meu, o Nosso Rio, Abençoado por Deus e Bonito por Natureza! ""O meu paraíso tem vista pro mar De Braços abertos vou abençoar O Pão de Açúcar, inspiração Estampado no meu pavilhão"" Sou carioca e São Clemente Irreverente, minha paixão Meu Rio sua beleza inspira o mar azul Canta Zona Sul! (2x) E Deus fez a maravilha Mistérios brotam deste chão Que a natureza esculpiu Divina emoção O Rio nasceu no sol da canção Terra cobiçada, iluminada Gente feliz Menina dos olhos Do Pai Criador Que o padroeiro abençoou Nas suas águas me banhar Da fonte vou beber E nesse império tropical Amanhecer (2x) Passo a passo... Civilização O modernismo surgiu Entre riscos e traços se rebatizou Cidade maravilhosa! ""Minha alma canta"", de tanta emoção A bossa embala, o ""tom"" da canção Preservar! É o caminho vamos respeitar Ser carioca é saber cuidar Do patrimônio mundial Rio, seu pôr-do-sol é um poema Braços abertos entra em cena Nesse carnaval! Sou carioca e São Clemente Irreverente, minha paixão Meu Rio sua beleza inspira o mar azul Canta Zona Sul! (2x)'),
      (1,2011,10,'0:30:00',10,10,'presentó un cuento sobre una isla encantada que representa a Florianópolis, capital del estado de Santa Catarina, en el sur del país','Y-Jurerê Mirim - A Encantadora Ilha das Bruxas (Um conto de Cascaes) Y-Jurerê mirim Meu paraíso, que maravilha! Foi Deus quem fez assim Com todo encanto, essa magia Entre contos e lendas Quanta imaginação Celebrando a natureza Rituais de gratidão Eu também sou carijó É bendito o meu lugar Rezei forte nesse chão Sai pra lá assombração Já peguei meu patuá Caldeirão vai ferver A Grande Rio chegou Vem trazer pra você Uma porção de amor É a receita que a bruxinha ensinou O folclore é tradição Valorizando a cultura popular O canto, a dança O sagrado e o profano Minha ilha encantada Vivo te admirando Beleza, riqueza Repousando sobre o mar Santuário pra sonhar Meu Rio te abraça, Floripa tão bela A tua história virou carnaval Essa ponte é a luz na passarela É obra-prima esse cartão postal'),
      (1,2011,11,'23:20:00',3,11,'""Río, azul del color del mar"", sobre la navegación marítima,','Rio, Azul da Cor do Mar Brilhou no céu A luz da águia, a estrela-guia Do coração navegador Que na travessia enfrentou Todo o medo que havia Era só mitologia do mar A lenda deu lugar para a certeza Que pra viver é preciso navegar As galés do oriente já vêm Da Fenícia e do Egito também Gregos e romanos partem para conquistar E o Farol da Alexandria fez a noite clarear Os mistérios vão desvendar Um novo caminho encontrar Lá na Índia, especiarias Leva-e-traz mercadorias A ambição do europeu se encantou Com o novo mundo de riqueza natural, sem igual Os navios negreiros Deixam seus lamentos pelo ar Nas águas de Iemanjá Nem pirata aventureiro ou rei podem mandar Oi leval mar, oi leva Leva as jangadas numa nova direção O porto centenário abriu seus braços Na terra de São Sebastião Portela vai buscar no horizonte A eterna fonte de inspiração Um oceano de amor que virou arte E deságua na imaginação Lindo como o mar azul Meu grande amor, minha Portela A força do seu pavilhão vai me levar A navegar'),
      (1,2011,12,'21:00:00',7,12,'enredo (tema central) trató sobre la teoría de la evolución, inició su espectáculo con un actor representando al científico inglés Charles Darwin (1809-1882), de gruesas patillas y traje de época azul, según reportó la agencia italiana Ansa.','O Mistério da Vida Minha alegria vai girar o mundo Aventureira vai cruzando o mar Trazendo Darwin na memória Histórias vou desvendar Um relicário de beleza natural É o esplendor do carnaval Que maravilha, nessa terra vou desembarcar O show da Ilha vai começar No fundo do mar eu vi brotar Se multiplicar a vida Mistérios vão se revelar Nas águas que vão me levar... a caminhar A terra abriu um sorriso E o paraíso vai me ver chegar Seres estão antenados Pequenos alados bailando no ar Lindos animais na passarela E lá no céu, a mais linda aquarela Do alto surgiu diferente Não sei se é bicho, não sei se é gente? Somos frutos do mesmo lugar A árvore da vida vamos preservar Hoje eu quero brindar... a Ilha Nessa avenida dos sonhos brilhar O meu amanhã, só Deus saberá A vida vamos celebrar');

INSERT INTO ama_roles
VALUES(1,2,2011,1,'rey momo'),
(2,2,2011,5,'reina del carnaval'),
(11,11,2011,7,'carnavalesco'),
(12,2,2011,8,'carnavalesco'),
(13,2,2011,9,'carnavalesco'),
(28,11,2011,6,'carnavalesco'),
(16,1,2011,12,'carnavalesco'),
(37,2,2011,1,'mestre-sala'),
(38,2,2011,1,'porta-bandeira');

INSERT INTO ama_detalles_reservas
VALUES(1,1,2),
(2,2,2),
(3,3,1),
(4,4,3),
(5,5,4),
(6,6,5),
(7,7,7),
(8,8,3),
(9,9,2);

INSERT INTO ama_entradas
VALUES(1,2,2011,1,'12:00','2011-02-12'),
(2,2,2011,2,'5:00','2011-01-11'),
(3,2,2011,3,'8:00','2010-12-06'),
(4,10,2012,4,'9:00','2011-05-15'),
(5,10,2012,5,'15:00','2011-09-16'),
(6,10,2012,6,'16:00','2012-02-01'),
(7,6,2013,7,'10:00','2012-10-05'),
(8,6,2013,8,'14:00','2013-01-06'),
(9,6,2013,9,'13:00','2012-12-18');

INSERT INTO ama_hist_precios 
VALUES(1,1,2011,2,1,'2010-05-01',1990,'2011-04-27'),
(2,2,2011,2,2,'2010-05-01',312,'2011-04-27'),
(3,3,2011,2,3,'2010-05-01',131,'2011-04-27'),
(4,4,2012,10,4,'2011-06-01',2105,'2012-02-10'),
(5,5,2012,10,5,'2011-06-01',2105,'2012-02-10'),
(6,6,2012,10,6,'2011-06-01',99,'2012-02-10'),
(7,7,2013,6,7,'2012-05-01',266,'2013-02-01'),
(8,8,2013,6,8,'2012-05-01',1990,'2013-02-01'),
(9,9,2013,6,9,'2012-05-01',1690,'2013-02-01');
